name: 'Top Contributors Action'
description: 'Generates a list of top contributors'
author: 'Ivan Shakhorski'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  output:
    description: 'File path to write the karma leaderboard to (e.g., CONTRIBUTORS.md)'
    required: false
    default: 'CONTRIBUTORS.md'
  limit:
    description: 'Limit the number of top contributors (optional)'
    required: false
  marker_start:
    description: 'Start marker to identify where to insert content (e.g., <!-- TOP-CONTRIBUTORS-START -->) or leave empty to replace entire file'
    required: false
    default: ''
  marker_end:
    description: 'End marker to identify where content insertion should end (e.g., <!-- TOP-CONTRIBUTORS-END -->)'
    required: false
    default: ''
  exclude:
    description: 'JSON array of patterns or emails to exclude from the contributions count (e.g., ["bot@example.com", "dependabot", "*-bot"])'
    required: false
    default: '[]'
  organization:
    description: 'Organization name to analyze (when specified, contributions will be counted across all repositories)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'award'
  color: 'white'